apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
    type: server
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: "500m"
          memory: "256Mi"
        requests:
          cpu: "250m"
          memory: "128Mi"